In [249]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 90)

# Original Dataset #

In [250]:
df = pd.read_csv('Ames_HousePrice.csv')
df.shape

(2580, 82)

In [251]:
df.head(2)

,Unnamed: 0,PID,GrLivArea,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,909176150,856,126000,30,RL,NaN,7890,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,SWISU,Norm,Norm,1Fam,1Story,6,6,1939,1950,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,238.0,Unf,0.0,618.0,856.0,GasA,TA,Y,SBrkr,856,0,0,1.0,0.0,1,0,2,1,TA,4,Typ,1,Gd,Detchd,1939.0,Unf,2.0,399.0,TA,TA,Y,0,0,0,0,166,0,NaN,NaN,NaN,0,3,2010,WD,Normal
1,2,905476230,1049,139500,120,RL,42.0,4235,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,TwnhsE,1Story,5,5,1984,1984,Gable,CompShg,HdBoard,HdBoard,BrkFace,149.0,Gd,TA,CBlock,Gd,TA,Mn,GLQ,552.0,ALQ,393.0,104.0,1049.0,GasA,TA,Y,SBrkr,1049,0,0,1.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1984.0,Fin,1.0,266.0,TA,TA,Y,0,105,0,0,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal

In [253]:
df = df.drop(['Unnamed: 0'], axis=1)
df.shape

(2580, 81)

In [254]:
df.dtypes.value_counts()
#43 categorical
#27 + 11 = 38 numerical

object     43
int64      27
float64    11
dtype: int64

# i = Features with 'int64' Data Type #

In [255]:
i = df.select_dtypes('int64')
i

,PID,GrLivArea,SalePrice,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,909176150,856,126000,30,7890,6,6,1939,1950,856,0,0,1,0,2,1,4,1,0,0,0,0,166,0,0,3,2010
1,905476230,1049,139500,120,4235,5,5,1984,1984,1049,0,0,2,0,2,1,5,0,0,105,0,0,0,0,0,2,2009
2,911128020,1001,124900,30,6060,5,9,1930,2007,1001,0,0,1,0,2,1,5,0,154,0,42,86,0,0,0,11,2007
3,535377150,1039,114000,70,8146,4,8,1900,2003,717,322,0,1,0,2,1,6,0,0,0,168,0,111,0,0,5,2009
4,534177230,1665,227000,60,8400,8,6,2001,2001,810,855,0,2,1,3,1,6,0,0,45,0,0,0,0,0,11,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,903205040,952,121000,30,8854,6,6,1916,1950,952,0,0,1,0,2,1,4,1,0,98,0,0,40,0,0,5,2009
2576,905402060,1733,139600,20,13680,3,5,1955,1955,1733,0,0,2,0,4,1,8,1,0,0,0,0,0,0,0,6,2009
2577,909275030,2002,145000,90,6270,5,6,1949,1950,1001,1001,0,2,0,4,2,8,0,0,0,0,0,0,0,0,8,2007
2578,907192040,1842,217500,60,8826,7,5,2000,2000,985,857,0,2,1,3,1,7,1,193,96,0,0,0,0,0,7,2007
2579,906223180,1911,215000,60,9554,8,5,1993,1994,1065,846,0,2,1,3,1,8,1,182,81,0,0,0,0,0,9,2006

In [256]:
#Remove PID - It is only for geospatial identification
i = i.drop('PID', axis=1)
i

,GrLivArea,SalePrice,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,856,126000,30,7890,6,6,1939,1950,856,0,0,1,0,2,1,4,1,0,0,0,0,166,0,0,3,2010
1,1049,139500,120,4235,5,5,1984,1984,1049,0,0,2,0,2,1,5,0,0,105,0,0,0,0,0,2,2009
2,1001,124900,30,6060,5,9,1930,2007,1001,0,0,1,0,2,1,5,0,154,0,42,86,0,0,0,11,2007
3,1039,114000,70,8146,4,8,1900,2003,717,322,0,1,0,2,1,6,0,0,0,168,0,111,0,0,5,2009
4,1665,227000,60,8400,8,6,2001,2001,810,855,0,2,1,3,1,6,0,0,45,0,0,0,0,0,11,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,952,121000,30,8854,6,6,1916,1950,952,0,0,1,0,2,1,4,1,0,98,0,0,40,0,0,5,2009
2576,1733,139600,20,13680,3,5,1955,1955,1733,0,0,2,0,4,1,8,1,0,0,0,0,0,0,0,6,2009
2577,2002,145000,90,6270,5,6,1949,1950,1001,1001,0,2,0,4,2,8,0,0,0,0,0,0,0,0,8,2007
2578,1842,217500,60,8826,7,5,2000,2000,985,857,0,2,1,3,1,7,1,193,96,0,0,0,0,0,7,2007
2579,1911,215000,60,9554,8,5,1993,1994,1065,846,0,2,1,3,1,8,1,182,81,0,0,0,0,0,9,2006

### Convert Supposingly Numerical Cols To Categorical ###

In [257]:
#Convert 'MSSubClass', 'YrSold', 'MoSold' to Categorical Data Types
i['MSSubClass'] = i['MSSubClass'].astype(str)
i['YrSold'] = i['YrSold'].astype(str)
i['MoSold'] = i['MoSold'].astype(str)

In [258]:
i.dtypes.value_counts()

int64     23
object     3
dtype: int64

# f = Features with 'float64' Data Type #

In [259]:
f = df.select_dtypes('float64')
f

,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
0,NaN,0.0,238.0,0.0,618.0,856.0,1.0,0.0,1939.0,2.0,399.0
1,42.0,149.0,552.0,393.0,104.0,1049.0,1.0,0.0,1984.0,1.0,266.0
2,60.0,0.0,737.0,0.0,100.0,837.0,0.0,0.0,1930.0,1.0,216.0
3,80.0,0.0,0.0,0.0,405.0,405.0,0.0,0.0,1940.0,1.0,281.0
4,70.0,0.0,643.0,0.0,167.0,810.0,1.0,0.0,2001.0,2.0,528.0
...,...,...,...,...,...,...,...,...,...,...,...
2575,NaN,0.0,0.0,0.0,952.0,952.0,0.0,0.0,1916.0,1.0,192.0
2576,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955.0,2.0,452.0
2577,82.0,0.0,284.0,0.0,717.0,1001.0,0.0,0.0,1949.0,3.0,871.0
2578,NaN,144.0,841.0,0.0,144.0,985.0,1.0,0.0,2000.0,2.0,486.0
2579,80.0,125.0,380.0,0.0,397.0,777.0,0.0,0.0,1993.0,2.0,471.0

# c = Features with 'object' Data Type #

In [260]:
c = df.select_dtypes('object')
df = pd.concat([c,f,i], axis=1)

In [261]:
c = df.select_dtypes('object')
c

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition,MSSubClass,MoSold,YrSold
0,RL,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,SWISU,Norm,Norm,1Fam,1Story,Gable,CompShg,Wd Sdng,Wd Sdng,None,TA,TA,CBlock,TA,TA,No,Rec,Unf,GasA,TA,Y,SBrkr,TA,Typ,Gd,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal,30,3,2010
1,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,TwnhsE,1Story,Gable,CompShg,HdBoard,HdBoard,BrkFace,Gd,TA,CBlock,Gd,TA,Mn,GLQ,ALQ,GasA,TA,Y,SBrkr,Gd,Typ,NaN,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal,120,2,2009
2,C (all),Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,None,Gd,TA,BrkTil,TA,TA,No,ALQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,NaN,Detchd,Unf,TA,Po,N,NaN,NaN,NaN,WD,Normal,30,11,2007
3,RL,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Norm,Norm,1Fam,2Story,Gable,CompShg,MetalSd,MetalSd,None,Gd,Gd,BrkTil,Fa,TA,No,Unf,Unf,GasA,Gd,Y,SBrkr,TA,Typ,NaN,Detchd,Unf,TA,TA,N,NaN,NaN,NaN,WD,Normal,70,5,2009
4,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,None,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,NaN,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal,60,11,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,BrkSide,Norm,Norm,1Fam,1.5Unf,Gable,CompShg,Wd Sdng,Wd Sdng,None,TA,TA,BrkTil,TA,TA,No,Unf,Unf,Grav,Fa,N,FuseF,Fa,Typ,Gd,Detchd,Unf,Fa,Po,P,NaN,NaN,NaN,WD,Normal,30,5,2009
2576,RL,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,1Fam,1Story,Hip,CompShg,BrkFace,Wd Sdng,None,TA,TA,Slab,NaN,NaN,NaN,NaN,NaN,GasA,Ex,Y,FuseA,TA,Min2,Gd,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal,20,6,2009
2577,RH,Pave,NaN,Reg,HLS,AllPub,Inside,Gtl,Crawfor,Norm,Norm,Duplex,2Story,Gable,CompShg,MetalSd,MetalSd,None,TA,TA,CBlock,TA,TA,No,BLQ,Unf,GasA,TA,N,FuseA,TA,Typ,NaN,2Types,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal,90,8,2007
2578,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal,60,7,2007
2579,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal,60,9,2006

In [262]:
df.dtypes.value_counts()

#After Conversion: 
#46 categorical features
#23 + 11 = 34 numerical (of which 1 is target variable "SalePrice"), Thus 33 features.

object     46
int64      23
float64    11
dtype: int64

### 'Object' Features with Missing Values ###

In [263]:
c.isnull().sum(axis=0).sort_values(ascending=False)

PoolQC           2571
MiscFeature      2483
Alley            2412
Fence            2055
FireplaceQu      1241
GarageFinish      129
GarageQual        129
GarageCond        129
GarageType        127
BsmtExposure       71
BsmtFinType2       70
BsmtQual           69
BsmtCond           69
BsmtFinType1       69
MasVnrType         14
Electrical          1
PavedDrive          0
SaleType            0
SaleCondition       0
Heating             0
MSSubClass          0
MoSold              0
Functional          0
KitchenQual         0
CentralAir          0
HeatingQC           0
MSZoning            0
Street              0
Condition2          0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
BldgType            0
Foundation          0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
YrSold              0
dtype: int64

### Check if "NaN" implies "None" ###

In [264]:
c.PoolQC.value_counts(dropna=False)
#PoolQC: NA -> No Pool, impute with 'None'

NaN    2571
TA        3
Ex        2
Gd        2
Fa        2
Name: PoolQC, dtype: int64

In [265]:
c.MiscFeature.value_counts(dropna=False)
#MiscFeature: NA -> None, impute with 'None'

NaN     2483
Shed      88
Gar2       5
Othr       3
TenC       1
Name: MiscFeature, dtype: int64

In [266]:
c.Alley.value_counts(dropna=False)
#Alley: NA -> No alley access, impute with 'None'

NaN     2412
Grvl     105
Pave      63
Name: Alley, dtype: int64

In [267]:
c.Fence.value_counts(dropna=False)
#Fence: NA -> No Fence, impute with 'None'

NaN      2055
MnPrv     301
GdPrv     111
GdWo      103
MnWw       10
Name: Fence, dtype: int64

In [268]:
c.FireplaceQu.value_counts(dropna=False)
#Fireplace: NA -> No Fireplace, impute with 'None'

NaN    1241
Gd      619
TA      572
Fa       70
Po       43
Ex       35
Name: FireplaceQu, dtype: int64

In [269]:
c.GarageFinish.value_counts(dropna=False)
#GarageFinish: NA -> No Garage, impute with 'None'

Unf    1112
RFn     718
Fin     621
NaN     129
Name: GarageFinish, dtype: int64

In [270]:
c.GarageCond.value_counts(dropna=False)
#GarageCond: NA -> No Garage, impute with 'None'

TA     2356
NaN     129
Fa       67
Gd       14
Po       11
Ex        3
Name: GarageCond, dtype: int64

In [271]:
c.GarageQual.value_counts(dropna=False)
#GarageQual: NA -> No Garage, impute with 'None'

TA     2312
NaN     129
Fa      110
Gd       22
Po        4
Ex        3
Name: GarageQual, dtype: int64

In [272]:
c.GarageType.value_counts(dropna=False)
#GarageType: NA -> No Garage, impute with 'None'

Attchd     1527
Detchd      716
BuiltIn     153
NaN         127
Basment      27
2Types       21
CarPort       9
Name: GarageType, dtype: int64

In [273]:
c.BsmtExposure.value_counts(dropna=False)
#BsmtExposure: NA -> No Basement, impute with 'None'

No     1708
Av      344
Gd      242
Mn      215
NaN      71
Name: BsmtExposure, dtype: int64

In [274]:
c.BsmtFinType2.value_counts(dropna=False)
#BsmtFinType2: NA -> No Basement, impute with 'None'

Unf    2180
Rec      97
LwQ      84
NaN      70
BLQ      64
ALQ      53
GLQ      32
Name: BsmtFinType2, dtype: int64

In [275]:
c.BsmtFinType1.value_counts(dropna=False)
#BsmtFinType1: NA -> No Basement, impute with 'None'

GLQ    753
Unf    706
ALQ    397
Rec    265
BLQ    251
LwQ    139
NaN     69
Name: BsmtFinType1, dtype: int64

In [276]:
c.BsmtCond.value_counts(dropna=False)
#BsmtCond: NA -> No Basement, impute with 'None'

TA     2316
Gd      101
Fa       88
NaN      69
Ex        3
Po        3
Name: BsmtCond, dtype: int64

In [277]:
c.BsmtQual.value_counts(dropna=False)
#BsmtQual: NA -> No Basement, impute with 'None'

TA     1166
Gd     1077
Ex      188
Fa       78
NaN      69
Po        2
Name: BsmtQual, dtype: int64

In [278]:
c.MasVnrType.value_counts(dropna=False)
#MasVnrType: None -> None
#MasVnrType: NA doesn't imply 'None', but 'None' is the mode, impute with 'None'

None       1559
BrkFace     804
Stone       183
BrkCmn       20
NaN          14
Name: MasVnrType, dtype: int64

### If NaN implies "None" or "No Feature", replace it with "None": ###

In [279]:
#Create Copy of dataframe and 'None' Impute for selected features: 

c_new = c.copy()

for column in [
    'PoolQC',
    'MiscFeature',
    'Alley',
    'Fence',
    'FireplaceQu',
    'GarageFinish',
    'GarageCond',
    'GarageQual',
    'GarageType',
    'BsmtExposure',
    'BsmtFinType2',
    'BsmtFinType1',
    'BsmtCond',
    'BsmtQual',
    'MasVnrType'
]:
    
    c_new[column] = c[column].fillna('None')

### If NaN doesn't imply "None" or have a meaning, replace it with "Mode":

In [280]:
c.Electrical.value_counts(dropna=False)
#Electrical: Doesn't have a designated meaning for "NA", so we will 'mode' impute:

SBrkr    2365
FuseA     168
FuseF      39
FuseP       7
NaN         1
Name: Electrical, dtype: int64

In [281]:
#Electrical: Only feature to "mode" impute
c_new['Electrical'] = c['Electrical'].fillna(c['Electrical'].mode()[0])

In [282]:
c_new.Electrical.value_counts(dropna=False)

SBrkr    2366
FuseA     168
FuseF      39
FuseP       7
Name: Electrical, dtype: int64

### c_new is c (features with 'object' data type) without any missing values: ###

In [283]:
#c.isnull().sum(axis=0).sort_values(ascending=False)

In [284]:
#Cross check that c_new doesn't have any missing values: 

#c_new.isnull().sum(axis=0).sort_values(ascending=False)
c_new.isnull().sum(axis=0).sort_values(ascending=False).sum()

0

In [285]:
c_new

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition,MSSubClass,MoSold,YrSold
0,RL,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,SWISU,Norm,Norm,1Fam,1Story,Gable,CompShg,Wd Sdng,Wd Sdng,None,TA,TA,CBlock,TA,TA,No,Rec,Unf,GasA,TA,Y,SBrkr,TA,Typ,Gd,Detchd,Unf,TA,TA,Y,None,None,None,WD,Normal,30,3,2010
1,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,TwnhsE,1Story,Gable,CompShg,HdBoard,HdBoard,BrkFace,Gd,TA,CBlock,Gd,TA,Mn,GLQ,ALQ,GasA,TA,Y,SBrkr,Gd,Typ,None,Attchd,Fin,TA,TA,Y,None,None,None,WD,Normal,120,2,2009
2,C (all),Pave,None,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,None,Gd,TA,BrkTil,TA,TA,No,ALQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,None,Detchd,Unf,TA,Po,N,None,None,None,WD,Normal,30,11,2007
3,RL,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Norm,Norm,1Fam,2Story,Gable,CompShg,MetalSd,MetalSd,None,Gd,Gd,BrkTil,Fa,TA,No,Unf,Unf,GasA,Gd,Y,SBrkr,TA,Typ,None,Detchd,Unf,TA,TA,N,None,None,None,WD,Normal,70,5,2009
4,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,None,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,None,Attchd,Fin,TA,TA,Y,None,None,None,WD,Normal,60,11,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrkSide,Norm,Norm,1Fam,1.5Unf,Gable,CompShg,Wd Sdng,Wd Sdng,None,TA,TA,BrkTil,TA,TA,No,Unf,Unf,Grav,Fa,N,FuseF,Fa,Typ,Gd,Detchd,Unf,Fa,Po,P,None,None,None,WD,Normal,30,5,2009
2576,RL,Pave,None,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,1Fam,1Story,Hip,CompShg,BrkFace,Wd Sdng,None,TA,TA,Slab,None,None,None,None,None,GasA,Ex,Y,FuseA,TA,Min2,Gd,Attchd,Unf,TA,TA,Y,None,None,None,WD,Normal,20,6,2009
2577,RH,Pave,None,Reg,HLS,AllPub,Inside,Gtl,Crawfor,Norm,Norm,Duplex,2Story,Gable,CompShg,MetalSd,MetalSd,None,TA,TA,CBlock,TA,TA,No,BLQ,Unf,GasA,TA,N,FuseA,TA,Typ,None,2Types,Unf,TA,TA,Y,None,None,None,WD,Normal,90,8,2007
2578,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,Fin,TA,TA,Y,None,None,None,WD,Normal,60,7,2007
2579,RL,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,TA,Attchd,RFn,TA,TA,Y,None,None,None,WD,Normal,60,9,2006

### Apply Ordinal Encoding To Ordinal Features

In [286]:
c_new.ExterQual.value_counts(dropna=False)

TA    1636
Gd     841
Ex      73
Fa      30
Name: ExterQual, dtype: int64

In [287]:
c_new.ExterQual

0       TA
1       Gd
2       Gd
3       Gd
4       Gd
        ..
2575    TA
2576    TA
2577    TA
2578    Gd
2579    Gd
Name: ExterQual, Length: 2580, dtype: object

In [288]:
c_new.ExterQual.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}, inplace=True)

In [289]:
c_new.ExterQual.value_counts(dropna=False)

3    1636
4     841
5      73
2      30
Name: ExterQual, dtype: int64

In [290]:
c_new.select_dtypes(np.number)

      ExterQual
0             3
1             4
2             4
3             4
4             4
...         ...
2575          3
2576          3
2577          3
2578          4
2579          4

[2580 rows x 1 columns]

In [291]:
c_new.ExterCond.value_counts(dropna=False)

TA    2232
Gd     279
Fa      56
Ex      11
Po       2
Name: ExterCond, dtype: int64

In [292]:
c_new.ExterCond

0       TA
1       TA
2       TA
3       Gd
4       TA
        ..
2575    TA
2576    TA
2577    TA
2578    TA
2579    TA
Name: ExterCond, Length: 2580, dtype: object

In [293]:
c_new.ExterCond.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}, inplace=True)

In [294]:
c_new.ExterCond.value_counts(dropna=False)

3    2232
4     279
2      56
5      11
1       2
Name: ExterCond, dtype: int64

In [295]:
c_new.select_dtypes(np.number)

      ExterQual  ExterCond
0             3          3
1             4          3
2             4          3
3             4          4
4             4          3
...         ...        ...
2575          3          3
2576          3          3
2577          3          3
2578          4          3
2579          4          3

[2580 rows x 2 columns]

In [296]:
c_new.BsmtQual.value_counts(dropna=False)

TA      1166
Gd      1077
Ex       188
Fa        78
None      69
Po         2
Name: BsmtQual, dtype: int64

In [297]:
c_new.BsmtQual

0         TA
1         Gd
2         TA
3         Fa
4         Gd
        ...
2575      TA
2576    None
2577      TA
2578      Gd
2579      Gd
Name: BsmtQual, Length: 2580, dtype: object

In [298]:
c_new.BsmtQual.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5, 'None':0}, inplace=True)

In [299]:
c_new.BsmtQual.value_counts(dropna=False)

3    1166
4    1077
5     188
2      78
0      69
1       2
Name: BsmtQual, dtype: int64

In [300]:
c_new.select_dtypes(np.number)

      ExterQual  ExterCond  BsmtQual
0             3          3         3
1             4          3         4
2             4          3         3
3             4          4         2
4             4          3         4
...         ...        ...       ...
2575          3          3         3
2576          3          3         0
2577          3          3         3
2578          4          3         4
2579          4          3         4

[2580 rows x 3 columns]

In [301]:
c_new.BsmtCond.value_counts(dropna=False)

TA      2316
Gd       101
Fa        88
None      69
Ex         3
Po         3
Name: BsmtCond, dtype: int64

In [302]:
c_new.BsmtCond

0         TA
1         TA
2         TA
3         TA
4         TA
        ...
2575      TA
2576    None
2577      TA
2578      TA
2579      TA
Name: BsmtCond, Length: 2580, dtype: object

In [303]:
c_new.BsmtCond.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5, 'None':0}, inplace=True)

In [304]:
c_new.BsmtCond.value_counts(dropna=False)

3    2316
4     101
2      88
0      69
5       3
1       3
Name: BsmtCond, dtype: int64

In [305]:
c_new.select_dtypes(np.number)

      ExterQual  ExterCond  BsmtQual  BsmtCond
0             3          3         3         3
1             4          3         4         3
2             4          3         3         3
3             4          4         2         3
4             4          3         4         3
...         ...        ...       ...       ...
2575          3          3         3         3
2576          3          3         0         0
2577          3          3         3         3
2578          4          3         4         3
2579          4          3         4         3

[2580 rows x 4 columns]

In [306]:
c_new.HeatingQC.value_counts(dropna=False)

Ex    1293
TA     768
Gd     434
Fa      84
Po       1
Name: HeatingQC, dtype: int64

In [307]:
c_new.HeatingQC

0       TA
1       TA
2       Ex
3       Gd
4       Ex
        ..
2575    Fa
2576    Ex
2577    TA
2578    Ex
2579    Ex
Name: HeatingQC, Length: 2580, dtype: object

In [308]:
c_new.HeatingQC.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}, inplace=True)

In [309]:
c_new.select_dtypes(np.number)

      ExterQual  ExterCond  BsmtQual  BsmtCond  HeatingQC
0             3          3         3         3          3
1             4          3         4         3          3
2             4          3         3         3          5
3             4          4         2         3          4
4             4          3         4         3          5
...         ...        ...       ...       ...        ...
2575          3          3         3         3          2
2576          3          3         0         0          5
2577          3          3         3         3          3
2578          4          3         4         3          5
2579          4          3         4         3          5

[2580 rows x 5 columns]

In [310]:
c_new.KitchenQual.value_counts(dropna=False)

TA    1358
Gd    1017
Ex     142
Fa      62
Po       1
Name: KitchenQual, dtype: int64

In [311]:
c_new.KitchenQual

0       TA
1       Gd
2       Gd
3       TA
4       Gd
        ..
2575    Fa
2576    TA
2577    TA
2578    Gd
2579    Gd
Name: KitchenQual, Length: 2580, dtype: object

In [312]:
c_new.KitchenQual.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5}, inplace=True)

In [313]:
c_new.KitchenQual.value_counts(dropna=False)

3    1358
4    1017
5     142
2      62
1       1
Name: KitchenQual, dtype: int64

In [314]:
c_new.select_dtypes(np.number)

      ExterQual  ExterCond  BsmtQual  BsmtCond  HeatingQC  KitchenQual
0             3          3         3         3          3            3
1             4          3         4         3          3            4
2             4          3         3         3          5            4
3             4          4         2         3          4            3
4             4          3         4         3          5            4
...         ...        ...       ...       ...        ...          ...
2575          3          3         3         3          2            2
2576          3          3         0         0          5            3
2577          3          3         3         3          3            3
2578          4          3         4         3          5            4
2579          4          3         4         3          5            4

[2580 rows x 6 columns]

In [315]:
c_new.Functional.value_counts(dropna=False)

Typ     2399
Min2      66
Min1      57
Mod       32
Maj1      18
Maj2       7
Sal        1
Name: Functional, dtype: int64

In [316]:
c_new.Functional

0        Typ
1        Typ
2        Typ
3        Typ
4        Typ
        ...
2575     Typ
2576    Min2
2577     Typ
2578     Typ
2579     Typ
Name: Functional, Length: 2580, dtype: object

In [317]:
c_new.Functional.replace({'Sal':1, 'Sev': 2, 'Maj2':3, 'Maj1':4, 'Mod':5, 'Min2':6,
                          'Min1':7, 'Typ':8}, inplace=True)

In [318]:
c_new.Functional.value_counts(dropna=False)

8    2399
6      66
7      57
5      32
4      18
3       7
1       1
Name: Functional, dtype: int64

In [319]:
c_new.select_dtypes(np.number)

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional
0,3,3,3,3,3,3,8
1,4,3,4,3,3,4,8
2,4,3,3,3,5,4,8
3,4,4,2,3,4,3,8
4,4,3,4,3,5,4,8
...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8
2576,3,3,0,0,5,3,6
2577,3,3,3,3,3,3,8
2578,4,3,4,3,5,4,8
2579,4,3,4,3,5,4,8

In [320]:
c_new.FireplaceQu.value_counts(dropna=False)

None    1241
Gd       619
TA       572
Fa        70
Po        43
Ex        35
Name: FireplaceQu, dtype: int64

In [321]:
c_new.FireplaceQu

0         Gd
1       None
2       None
3       None
4       None
        ...
2575      Gd
2576      Gd
2577    None
2578      TA
2579      TA
Name: FireplaceQu, Length: 2580, dtype: object

In [322]:
c_new.FireplaceQu.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5, 'None':0}, inplace=True)

In [323]:
c_new.FireplaceQu.value_counts(dropna=False)

0    1241
4     619
3     572
2      70
1      43
5      35
Name: FireplaceQu, dtype: int64

In [324]:
c_new.select_dtypes(np.number)

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu
0,3,3,3,3,3,3,8,4
1,4,3,4,3,3,4,8,0
2,4,3,3,3,5,4,8,0
3,4,4,2,3,4,3,8,0
4,4,3,4,3,5,4,8,0
...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4
2576,3,3,0,0,5,3,6,4
2577,3,3,3,3,3,3,8,0
2578,4,3,4,3,5,4,8,3
2579,4,3,4,3,5,4,8,3

In [325]:
c_new.GarageFinish.value_counts(dropna=False)

Unf     1112
RFn      718
Fin      621
None     129
Name: GarageFinish, dtype: int64

In [326]:
c_new.GarageFinish

0       Unf
1       Fin
2       Unf
3       Unf
4       Fin
       ...
2575    Unf
2576    Unf
2577    Unf
2578    Fin
2579    RFn
Name: GarageFinish, Length: 2580, dtype: object

In [327]:
c_new.GarageFinish.replace({'Unf':1, 'RFn':2, 'Fin':3, 'None':0}, inplace=True)

In [328]:
c_new.GarageFinish.value_counts(dropna=False)

1    1112
2     718
3     621
0     129
Name: GarageFinish, dtype: int64

In [329]:
c_new.select_dtypes(np.number)

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu,GarageFinish
0,3,3,3,3,3,3,8,4,1
1,4,3,4,3,3,4,8,0,3
2,4,3,3,3,5,4,8,0,1
3,4,4,2,3,4,3,8,0,1
4,4,3,4,3,5,4,8,0,3
...,...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4,1
2576,3,3,0,0,5,3,6,4,1
2577,3,3,3,3,3,3,8,0,1
2578,4,3,4,3,5,4,8,3,3
2579,4,3,4,3,5,4,8,3,2

In [330]:
c_new.GarageQual.value_counts(dropna=False)

TA      2312
None     129
Fa       110
Gd        22
Po         4
Ex         3
Name: GarageQual, dtype: int64

In [331]:
c_new.GarageQual

0       TA
1       TA
2       TA
3       TA
4       TA
        ..
2575    Fa
2576    TA
2577    TA
2578    TA
2579    TA
Name: GarageQual, Length: 2580, dtype: object

In [332]:
c_new.GarageQual.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5, 'None':0}, inplace=True)

In [333]:
c_new.GarageQual.value_counts(dropna=False)

3    2312
0     129
2     110
4      22
1       4
5       3
Name: GarageQual, dtype: int64

In [334]:
c_new.select_dtypes(np.number)

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual
0,3,3,3,3,3,3,8,4,1,3
1,4,3,4,3,3,4,8,0,3,3
2,4,3,3,3,5,4,8,0,1,3
3,4,4,2,3,4,3,8,0,1,3
4,4,3,4,3,5,4,8,0,3,3
...,...,...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4,1,2
2576,3,3,0,0,5,3,6,4,1,3
2577,3,3,3,3,3,3,8,0,1,3
2578,4,3,4,3,5,4,8,3,3,3
2579,4,3,4,3,5,4,8,3,2,3

In [335]:
c_new.GarageCond.value_counts(dropna=False)

TA      2356
None     129
Fa        67
Gd        14
Po        11
Ex         3
Name: GarageCond, dtype: int64

In [336]:
c_new.GarageCond

0       TA
1       TA
2       Po
3       TA
4       TA
        ..
2575    Po
2576    TA
2577    TA
2578    TA
2579    TA
Name: GarageCond, Length: 2580, dtype: object

In [337]:
c_new.GarageCond.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5, 'None':0}, inplace=True)

In [338]:
c_new.GarageCond

0       3
1       3
2       1
3       3
4       3
       ..
2575    1
2576    3
2577    3
2578    3
2579    3
Name: GarageCond, Length: 2580, dtype: int64

In [339]:
c_new.select_dtypes(np.number)

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual,GarageCond
0,3,3,3,3,3,3,8,4,1,3,3
1,4,3,4,3,3,4,8,0,3,3,3
2,4,3,3,3,5,4,8,0,1,3,1
3,4,4,2,3,4,3,8,0,1,3,3
4,4,3,4,3,5,4,8,0,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4,1,2,1
2576,3,3,0,0,5,3,6,4,1,3,3
2577,3,3,3,3,3,3,8,0,1,3,3
2578,4,3,4,3,5,4,8,3,3,3,3
2579,4,3,4,3,5,4,8,3,2,3,3

In [340]:
c_new.PoolQC.value_counts(dropna=False)

None    2571
TA         3
Ex         2
Gd         2
Fa         2
Name: PoolQC, dtype: int64

In [341]:
c_new.PoolQC

0       None
1       None
2       None
3       None
4       None
        ...
2575    None
2576    None
2577    None
2578    None
2579    None
Name: PoolQC, Length: 2580, dtype: object

In [342]:
c_new.PoolQC.replace({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5, 'None':0}, inplace=True)

In [343]:
c_new_ordinal_encoded = c_new.select_dtypes(np.number)
c_new_ordinal_encoded

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual,GarageCond,PoolQC
0,3,3,3,3,3,3,8,4,1,3,3,0
1,4,3,4,3,3,4,8,0,3,3,3,0
2,4,3,3,3,5,4,8,0,1,3,1,0
3,4,4,2,3,4,3,8,0,1,3,3,0
4,4,3,4,3,5,4,8,0,3,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4,1,2,1,0
2576,3,3,0,0,5,3,6,4,1,3,3,0
2577,3,3,3,3,3,3,8,0,1,3,3,0
2578,4,3,4,3,5,4,8,3,3,3,3,0
2579,4,3,4,3,5,4,8,3,2,3,3,0

### Label Encode Non-Ordinal Categorical Features ###

In [344]:
c_new.select_dtypes('object')

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,CentralAir,Electrical,GarageType,PavedDrive,Fence,MiscFeature,SaleType,SaleCondition,MSSubClass,MoSold,YrSold
0,RL,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,SWISU,Norm,Norm,1Fam,1Story,Gable,CompShg,Wd Sdng,Wd Sdng,None,CBlock,No,Rec,Unf,GasA,Y,SBrkr,Detchd,Y,None,None,WD,Normal,30,3,2010
1,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,TwnhsE,1Story,Gable,CompShg,HdBoard,HdBoard,BrkFace,CBlock,Mn,GLQ,ALQ,GasA,Y,SBrkr,Attchd,Y,None,None,WD,Normal,120,2,2009
2,C (all),Pave,None,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,None,BrkTil,No,ALQ,Unf,GasA,Y,SBrkr,Detchd,N,None,None,WD,Normal,30,11,2007
3,RL,Pave,None,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Norm,Norm,1Fam,2Story,Gable,CompShg,MetalSd,MetalSd,None,BrkTil,No,Unf,Unf,GasA,Y,SBrkr,Detchd,N,None,None,WD,Normal,70,5,2009
4,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,None,PConc,No,GLQ,Unf,GasA,Y,SBrkr,Attchd,Y,None,None,WD,Normal,60,11,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,BrkSide,Norm,Norm,1Fam,1.5Unf,Gable,CompShg,Wd Sdng,Wd Sdng,None,BrkTil,No,Unf,Unf,Grav,N,FuseF,Detchd,P,None,None,WD,Normal,30,5,2009
2576,RL,Pave,None,IR1,Lvl,AllPub,CulDSac,Gtl,Edwards,Norm,Norm,1Fam,1Story,Hip,CompShg,BrkFace,Wd Sdng,None,Slab,None,None,None,GasA,Y,FuseA,Attchd,Y,None,None,WD,Normal,20,6,2009
2577,RH,Pave,None,Reg,HLS,AllPub,Inside,Gtl,Crawfor,Norm,Norm,Duplex,2Story,Gable,CompShg,MetalSd,MetalSd,None,CBlock,No,BLQ,Unf,GasA,N,FuseA,2Types,Y,None,None,WD,Normal,90,8,2007
2578,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,PConc,No,GLQ,Unf,GasA,Y,SBrkr,Attchd,Y,None,None,WD,Normal,60,7,2007
2579,RL,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,BrkFace,PConc,No,GLQ,Unf,GasA,Y,SBrkr,Attchd,Y,None,None,WD,Normal,60,9,2006

In [345]:
from sklearn.preprocessing import OrdinalEncoder

In [346]:
C = c_new.select_dtypes('object').values
C

array([['RL', 'Pave', 'None', ..., '30', '3', '2010'],
       ['RL', 'Pave', 'None', ..., '120', '2', '2009'],
       ['C (all)', 'Pave', 'None', ..., '30', '11', '2007'],
       ...,
       ['RH', 'Pave', 'None', ..., '90', '8', '2007'],
       ['RL', 'Pave', 'None', ..., '60', '7', '2007'],
       ['RL', 'Pave', 'None', ..., '60', '9', '2006']], dtype=object)

In [347]:
ordinal_encode = OrdinalEncoder()
C = ordinal_encode.fit_transform(C)

In [348]:
C

array([[ 5.,  1.,  1., ...,  6.,  5.,  4.],
       [ 5.,  1.,  1., ...,  0.,  4.,  3.],
       [ 1.,  1.,  1., ...,  6.,  2.,  1.],
       ...,
       [ 4.,  1.,  1., ..., 15., 10.,  1.],
       [ 5.,  1.,  1., ..., 10.,  9.,  1.],
       [ 5.,  1.,  1., ..., 10., 11.,  0.]])

In [349]:
c_new_encoded = pd.DataFrame(C, columns=c_new.select_dtypes('object').columns)
c_new_encoded

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,CentralAir,Electrical,GarageType,PavedDrive,Fence,MiscFeature,SaleType,SaleCondition,MSSubClass,MoSold,YrSold
0,5.0,1.0,1.0,3.0,3.0,0.0,0.0,0.0,21.0,2.0,2.0,0.0,2.0,1.0,0.0,13.0,14.0,2.0,1.0,3.0,5.0,6.0,1.0,1.0,3.0,5.0,2.0,4.0,1.0,9.0,4.0,6.0,5.0,4.0
1,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,7.0,2.0,2.0,4.0,2.0,1.0,0.0,6.0,6.0,1.0,1.0,2.0,2.0,0.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,0.0,4.0,3.0
2,1.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,11.0,2.0,2.0,0.0,2.0,3.0,0.0,8.0,8.0,2.0,0.0,3.0,0.0,6.0,1.0,1.0,3.0,5.0,0.0,4.0,1.0,9.0,4.0,6.0,2.0,1.0
3,5.0,1.0,1.0,3.0,3.0,0.0,0.0,0.0,20.0,2.0,2.0,0.0,5.0,1.0,0.0,8.0,8.0,2.0,0.0,3.0,6.0,6.0,1.0,1.0,3.0,5.0,0.0,4.0,1.0,9.0,4.0,11.0,7.0,3.0
4,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,17.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,2.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,3.0,2.0,2.0,0.0,1.0,1.0,0.0,13.0,14.0,2.0,0.0,3.0,6.0,6.0,3.0,0.0,1.0,5.0,1.0,4.0,1.0,9.0,4.0,6.0,7.0,3.0
2576,5.0,1.0,1.0,0.0,3.0,0.0,1.0,0.0,7.0,2.0,2.0,0.0,2.0,3.0,0.0,3.0,14.0,2.0,3.0,4.0,4.0,4.0,1.0,1.0,0.0,1.0,2.0,4.0,1.0,9.0,4.0,5.0,8.0,3.0
2577,4.0,1.0,1.0,3.0,1.0,0.0,4.0,0.0,6.0,2.0,2.0,2.0,5.0,1.0,0.0,8.0,8.0,2.0,1.0,3.0,1.0,6.0,1.0,0.0,0.0,0.0,2.0,4.0,1.0,9.0,4.0,15.0,10.0,1.0
2578,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,5.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,1.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,9.0,1.0
2579,5.0,1.0,1.0,0.0,3.0,0.0,4.0,0.0,23.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,1.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,11.0,0.0

In [350]:
c_new_fully_encoded = pd.concat([c_new_ordinal_encoded, c_new_encoded], axis=1)
c_new_fully_encoded

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual,GarageCond,PoolQC,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,CentralAir,Electrical,GarageType,PavedDrive,Fence,MiscFeature,SaleType,SaleCondition,MSSubClass,MoSold,YrSold
0,3,3,3,3,3,3,8,4,1,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,0.0,0.0,21.0,2.0,2.0,0.0,2.0,1.0,0.0,13.0,14.0,2.0,1.0,3.0,5.0,6.0,1.0,1.0,3.0,5.0,2.0,4.0,1.0,9.0,4.0,6.0,5.0,4.0
1,4,3,4,3,3,4,8,0,3,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,7.0,2.0,2.0,4.0,2.0,1.0,0.0,6.0,6.0,1.0,1.0,2.0,2.0,0.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,0.0,4.0,3.0
2,4,3,3,3,5,4,8,0,1,3,1,0,1.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,11.0,2.0,2.0,0.0,2.0,3.0,0.0,8.0,8.0,2.0,0.0,3.0,0.0,6.0,1.0,1.0,3.0,5.0,0.0,4.0,1.0,9.0,4.0,6.0,2.0,1.0
3,4,4,2,3,4,3,8,0,1,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,0.0,0.0,20.0,2.0,2.0,0.0,5.0,1.0,0.0,8.0,8.0,2.0,0.0,3.0,6.0,6.0,1.0,1.0,3.0,5.0,0.0,4.0,1.0,9.0,4.0,11.0,7.0,3.0
4,4,3,4,3,5,4,8,0,3,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,17.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,2.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4,1,2,1,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,3.0,2.0,2.0,0.0,1.0,1.0,0.0,13.0,14.0,2.0,0.0,3.0,6.0,6.0,3.0,0.0,1.0,5.0,1.0,4.0,1.0,9.0,4.0,6.0,7.0,3.0
2576,3,3,0,0,5,3,6,4,1,3,3,0,5.0,1.0,1.0,0.0,3.0,0.0,1.0,0.0,7.0,2.0,2.0,0.0,2.0,3.0,0.0,3.0,14.0,2.0,3.0,4.0,4.0,4.0,1.0,1.0,0.0,1.0,2.0,4.0,1.0,9.0,4.0,5.0,8.0,3.0
2577,3,3,3,3,3,3,8,0,1,3,3,0,4.0,1.0,1.0,3.0,1.0,0.0,4.0,0.0,6.0,2.0,2.0,2.0,5.0,1.0,0.0,8.0,8.0,2.0,1.0,3.0,1.0,6.0,1.0,0.0,0.0,0.0,2.0,4.0,1.0,9.0,4.0,15.0,10.0,1.0
2578,4,3,4,3,5,4,8,3,3,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,5.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,1.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,9.0,1.0
2579,4,3,4,3,5,4,8,3,2,3,3,0,5.0,1.0,1.0,0.0,3.0,0.0,4.0,0.0,23.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,1.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,11.0,0.0

# Mean Impute Missing Values For i and f #

In [351]:
#Check initial data types by column
n = pd.concat([i,f], axis=1)
n.dtypes.value_counts()

int64      23
float64    11
object      3
dtype: int64

In [352]:
#Retain only numeric data types (c and c_new has all "object" datatypes)
n = n.select_dtypes(np.number)
n.dtypes.value_counts()

int64      23
float64    11
dtype: int64

In [353]:
#len(numeric.isnull().sum(axis=0).sort_values(ascending=False))
n.isnull().sum(axis=0).sort_values(ascending=False)

LotFrontage      462
GarageYrBlt      129
MasVnrArea        14
BsmtHalfBath       2
BsmtFullBath       2
GarageArea         1
BsmtFinSF1         1
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
GarageCars         1
SalePrice          0
MiscVal            0
PoolArea           0
ScreenPorch        0
3SsnPorch          0
EnclosedPorch      0
GrLivArea          0
WoodDeckSF         0
Fireplaces         0
TotRmsAbvGrd       0
KitchenAbvGr       0
BedroomAbvGr       0
HalfBath           0
FullBath           0
LowQualFinSF       0
2ndFlrSF           0
1stFlrSF           0
YearRemodAdd       0
YearBuilt          0
OverallCond        0
OverallQual        0
LotArea            0
OpenPorchSF        0
dtype: int64

In [354]:
n

,GrLivArea,SalePrice,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
0,856,126000,7890,6,6,1939,1950,856,0,0,1,0,2,1,4,1,0,0,0,0,166,0,0,NaN,0.0,238.0,0.0,618.0,856.0,1.0,0.0,1939.0,2.0,399.0
1,1049,139500,4235,5,5,1984,1984,1049,0,0,2,0,2,1,5,0,0,105,0,0,0,0,0,42.0,149.0,552.0,393.0,104.0,1049.0,1.0,0.0,1984.0,1.0,266.0
2,1001,124900,6060,5,9,1930,2007,1001,0,0,1,0,2,1,5,0,154,0,42,86,0,0,0,60.0,0.0,737.0,0.0,100.0,837.0,0.0,0.0,1930.0,1.0,216.0
3,1039,114000,8146,4,8,1900,2003,717,322,0,1,0,2,1,6,0,0,0,168,0,111,0,0,80.0,0.0,0.0,0.0,405.0,405.0,0.0,0.0,1940.0,1.0,281.0
4,1665,227000,8400,8,6,2001,2001,810,855,0,2,1,3,1,6,0,0,45,0,0,0,0,0,70.0,0.0,643.0,0.0,167.0,810.0,1.0,0.0,2001.0,2.0,528.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,952,121000,8854,6,6,1916,1950,952,0,0,1,0,2,1,4,1,0,98,0,0,40,0,0,NaN,0.0,0.0,0.0,952.0,952.0,0.0,0.0,1916.0,1.0,192.0
2576,1733,139600,13680,3,5,1955,1955,1733,0,0,2,0,4,1,8,1,0,0,0,0,0,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955.0,2.0,452.0
2577,2002,145000,6270,5,6,1949,1950,1001,1001,0,2,0,4,2,8,0,0,0,0,0,0,0,0,82.0,0.0,284.0,0.0,717.0,1001.0,0.0,0.0,1949.0,3.0,871.0
2578,1842,217500,8826,7,5,2000,2000,985,857,0,2,1,3,1,7,1,193,96,0,0,0,0,0,NaN,144.0,841.0,0.0,144.0,985.0,1.0,0.0,2000.0,2.0,486.0
2579,1911,215000,9554,8,5,1993,1994,1065,846,0,2,1,3,1,8,1,182,81,0,0,0,0,0,80.0,125.0,380.0,0.0,397.0,777.0,0.0,0.0,1993.0,2.0,471.0

In [355]:
nan_cols = [col for col in n.columns if n[col].isnull().any()]
nan_cols

['LotFrontage',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea']

In [356]:
n[nan_cols].isna().sum()

LotFrontage     462
MasVnrArea       14
BsmtFinSF1        1
BsmtFinSF2        1
BsmtUnfSF         1
TotalBsmtSF       1
BsmtFullBath      2
BsmtHalfBath      2
GarageYrBlt     129
GarageCars        1
GarageArea        1
dtype: int64

In [357]:
Rows_w_Nan = n[n[nan_cols].isna().any(axis=1)]
Index = Rows_w_Nan.index
Rows_w_Nan

,GrLivArea,SalePrice,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
0,856,126000,7890,6,6,1939,1950,856,0,0,1,0,2,1,4,1,0,0,0,0,166,0,0,NaN,0.0,238.0,0.0,618.0,856.0,1.0,0.0,1939.0,2.0,399.0
13,1394,159000,9500,6,5,1963,1963,1394,0,0,1,1,3,1,6,2,0,76,0,0,185,0,0,NaN,247.0,609.0,0.0,785.0,1394.0,1.0,0.0,1963.0,2.0,514.0
17,864,67000,8248,3,3,1914,1950,864,0,0,1,0,2,1,5,0,0,0,100,0,0,0,0,45.0,0.0,41.0,0.0,823.0,864.0,1.0,0.0,NaN,0.0,0.0
18,1610,205000,10603,6,7,1977,2001,1610,0,0,2,0,3,1,6,2,168,68,0,0,0,0,0,NaN,28.0,1200.0,0.0,410.0,1610.0,1.0,0.0,1977.0,2.0,480.0
22,1092,98000,1477,6,9,1970,2007,546,546,0,2,1,3,1,6,0,187,0,0,0,0,0,0,21.0,0.0,358.0,0.0,188.0,546.0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2561,1482,163900,9125,7,5,1992,1992,812,670,0,2,1,3,1,7,1,100,25,0,0,0,0,0,NaN,170.0,0.0,0.0,384.0,384.0,0.0,0.0,1992.0,2.0,392.0
2563,1584,119000,8917,5,5,1967,1967,1584,0,0,2,0,4,2,8,0,0,0,0,0,0,0,0,NaN,0.0,0.0,0.0,1584.0,1584.0,0.0,0.0,1967.0,2.0,506.0
2575,952,121000,8854,6,6,1916,1950,952,0,0,1,0,2,1,4,1,0,98,0,0,40,0,0,NaN,0.0,0.0,0.0,952.0,952.0,0.0,0.0,1916.0,1.0,192.0
2576,1733,139600,13680,3,5,1955,1955,1733,0,0,2,0,4,1,8,1,0,0,0,0,0,0,0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955.0,2.0,452.0
2578,1842,217500,8826,7,5,2000,2000,985,857,0,2,1,3,1,7,1,193,96,0,0,0,0,0,NaN,144.0,841.0,0.0,144.0,985.0,1.0,0.0,2000.0,2.0,486.0

In [358]:
NanDF = Rows_w_Nan[nan_cols]
NanDF

,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
0,NaN,0.0,238.0,0.0,618.0,856.0,1.0,0.0,1939.0,2.0,399.0
13,NaN,247.0,609.0,0.0,785.0,1394.0,1.0,0.0,1963.0,2.0,514.0
17,45.0,0.0,41.0,0.0,823.0,864.0,1.0,0.0,NaN,0.0,0.0
18,NaN,28.0,1200.0,0.0,410.0,1610.0,1.0,0.0,1977.0,2.0,480.0
22,21.0,0.0,358.0,0.0,188.0,546.0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2561,NaN,170.0,0.0,0.0,384.0,384.0,0.0,0.0,1992.0,2.0,392.0
2563,NaN,0.0,0.0,0.0,1584.0,1584.0,0.0,0.0,1967.0,2.0,506.0
2575,NaN,0.0,0.0,0.0,952.0,952.0,0.0,0.0,1916.0,1.0,192.0
2576,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955.0,2.0,452.0
2578,NaN,144.0,841.0,0.0,144.0,985.0,1.0,0.0,2000.0,2.0,486.0

In [359]:
n[nan_cols].describe()

,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
count,2118.000000,2566.000000,2579.000000,2579.000000,2579.000000,2579.000000,2578.000000,2578.000000,2451.000000,2579.000000,2579.000000
mean,68.516053,99.308262,444.346258,53.238852,539.101590,1036.686700,0.435221,0.062064,1976.982048,1.747577,466.842575
std,22.835831,175.872330,429.334957,174.423920,425.199639,418.555417,0.518827,0.244513,24.659801,0.738678,207.476842
min,21.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1895.000000,0.000000,0.000000
25%,57.000000,0.000000,0.000000,0.000000,215.000000,792.000000,0.000000,0.000000,1960.000000,1.000000,318.000000
50%,68.000000,0.000000,384.000000,0.000000,448.000000,979.000000,0.000000,0.000000,1978.000000,2.000000,474.000000
75%,80.000000,158.000000,732.000000,0.000000,784.000000,1266.500000,1.000000,0.000000,2000.000000,2.000000,576.000000
max,313.000000,1600.000000,2288.000000,1526.000000,2336.000000,3206.000000,3.000000,2.000000,2010.000000,5.000000,1488.000000

In [360]:
n[nan_cols].mean()

LotFrontage       68.516053
MasVnrArea        99.308262
BsmtFinSF1       444.346258
BsmtFinSF2        53.238852
BsmtUnfSF        539.101590
TotalBsmtSF     1036.686700
BsmtFullBath       0.435221
BsmtHalfBath       0.062064
GarageYrBlt     1976.982048
GarageCars         1.747577
GarageArea       466.842575
dtype: float64

In [361]:
n_new = n.copy()

for cols in nan_cols:
    mean_value = n[cols].mean()
    n_new[cols] = n[cols].fillna(value=mean_value)
    print (cols, mean_value)

LotFrontage 68.51605288007555
MasVnrArea 99.3082618862042
BsmtFinSF1 444.3462582396278
BsmtFinSF2 53.238852268321054
BsmtUnfSF 539.1015897634742
TotalBsmtSF 1036.686700271423
BsmtFullBath 0.4352211016291699
BsmtHalfBath 0.062063615205585725
GarageYrBlt 1976.9820481436147
GarageCars 1.7475765800697944
GarageArea 466.84257464133384

In [362]:
nan_cols

['LotFrontage',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea']

In [363]:
n_new.shape

(2580, 34)

In [364]:
n_new.describe()

,GrLivArea,SalePrice,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
count,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.00000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000,2580.000000
mean,1486.039922,178059.623256,10120.153488,6.046124,5.618605,1970.313953,1983.751938,1144.975194,336.820155,4.244574,1.550775,0.378295,2.850388,1.04031,6.387209,0.604264,95.919767,46.085271,23.214341,2.511240,16.200388,1.662016,48.731395,68.516053,99.308262,444.346258,53.238852,539.101590,1036.686700,0.435221,0.062064,1976.982048,1.747577,466.842575
std,488.650181,75031.089374,8126.937892,1.367590,1.122008,29.719705,20.490242,375.958955,424.072452,44.403603,0.545825,0.499237,0.822863,0.20255,1.535186,0.648604,129.052016,66.060664,64.107825,25.293935,56.824783,30.339396,498.725058,20.689575,175.394322,429.251712,174.390101,425.117196,418.474262,0.518626,0.244418,24.035156,0.738535,207.436614
min,334.000000,12789.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1895.000000,0.000000,0.000000
25%,1112.000000,129975.000000,7406.750000,5.000000,5.000000,1953.000000,1965.000000,871.750000,0.000000,0.000000,1.000000,0.000000,2.000000,1.00000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,0.000000,0.000000,215.000000,792.000000,0.000000,0.000000,1961.000000,1.000000,318.000000
50%,1436.000000,159900.000000,9391.000000,6.000000,5.000000,1972.000000,1992.000000,1071.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.00000,6.000000,1.000000,0.000000,25.500000,0.000000,0.000000,0.000000,0.000000,0.000000,68.516053,0.000000,384.500000,0.000000,448.000000,979.500000,0.000000,0.000000,1977.000000,2.000000,474.000000
75%,1733.000000,209625.000000,11494.000000,7.000000,6.000000,1999.000000,2003.000000,1364.000000,703.000000,0.000000,2.000000,1.000000,3.000000,1.00000,7.000000,1.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,78.000000,157.000000,732.000000,0.000000,784.000000,1266.250000,1.000000,0.000000,1999.000000,2.000000,576.000000
max,4676.000000,755000.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,3820.000000,1872.000000,1064.000000,4.000000,2.000000,6.000000,3.00000,13.000000,4.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,15500.000000,313.000000,1600.000000,2288.000000,1526.000000,2336.000000,3206.000000,3.000000,2.000000,2010.000000,5.000000,1488.000000

In [365]:
n_new.isnull().sum().sum()

0

In [366]:
n.isnull().sum().sum()

615

# Combine c_new_fully_encoded, n_new into df_new, No Missing Values

In [367]:
new_df = pd.concat([c_new_fully_encoded, n_new], axis=1)
new_df.dtypes.value_counts()

float64    45
int64      35
dtype: int64

In [368]:
new_df.isnull().sum().sum()

0

In [369]:
new_df

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,Functional,FireplaceQu,GarageFinish,GarageQual,GarageCond,PoolQC,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,Foundation,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,CentralAir,Electrical,GarageType,PavedDrive,Fence,MiscFeature,SaleType,SaleCondition,MSSubClass,MoSold,YrSold,GrLivArea,SalePrice,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,LotFrontage,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,BsmtFullBath,BsmtHalfBath,GarageYrBlt,GarageCars,GarageArea
0,3,3,3,3,3,3,8,4,1,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,0.0,0.0,21.0,2.0,2.0,0.0,2.0,1.0,0.0,13.0,14.0,2.0,1.0,3.0,5.0,6.0,1.0,1.0,3.0,5.0,2.0,4.0,1.0,9.0,4.0,6.0,5.0,4.0,856,126000,7890,6,6,1939,1950,856,0,0,1,0,2,1,4,1,0,0,0,0,166,0,0,68.516053,0.0,238.0,0.0,618.0,856.0,1.0,0.0,1939.0,2.0,399.0
1,4,3,4,3,3,4,8,0,3,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,7.0,2.0,2.0,4.0,2.0,1.0,0.0,6.0,6.0,1.0,1.0,2.0,2.0,0.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,0.0,4.0,3.0,1049,139500,4235,5,5,1984,1984,1049,0,0,2,0,2,1,5,0,0,105,0,0,0,0,0,42.000000,149.0,552.0,393.0,104.0,1049.0,1.0,0.0,1984.0,1.0,266.0
2,4,3,3,3,5,4,8,0,1,3,1,0,1.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,11.0,2.0,2.0,0.0,2.0,3.0,0.0,8.0,8.0,2.0,0.0,3.0,0.0,6.0,1.0,1.0,3.0,5.0,0.0,4.0,1.0,9.0,4.0,6.0,2.0,1.0,1001,124900,6060,5,9,1930,2007,1001,0,0,1,0,2,1,5,0,154,0,42,86,0,0,0,60.000000,0.0,737.0,0.0,100.0,837.0,0.0,0.0,1930.0,1.0,216.0
3,4,4,2,3,4,3,8,0,1,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,0.0,0.0,20.0,2.0,2.0,0.0,5.0,1.0,0.0,8.0,8.0,2.0,0.0,3.0,6.0,6.0,1.0,1.0,3.0,5.0,0.0,4.0,1.0,9.0,4.0,11.0,7.0,3.0,1039,114000,8146,4,8,1900,2003,717,322,0,1,0,2,1,6,0,0,0,168,0,111,0,0,80.000000,0.0,0.0,0.0,405.0,405.0,0.0,0.0,1940.0,1.0,281.0
4,4,3,4,3,5,4,8,0,3,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,17.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,2.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,2.0,3.0,1665,227000,8400,8,6,2001,2001,810,855,0,2,1,3,1,6,0,0,45,0,0,0,0,0,70.000000,0.0,643.0,0.0,167.0,810.0,1.0,0.0,2001.0,2.0,528.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2575,3,3,3,3,2,2,8,4,1,2,1,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,3.0,2.0,2.0,0.0,1.0,1.0,0.0,13.0,14.0,2.0,0.0,3.0,6.0,6.0,3.0,0.0,1.0,5.0,1.0,4.0,1.0,9.0,4.0,6.0,7.0,3.0,952,121000,8854,6,6,1916,1950,952,0,0,1,0,2,1,4,1,0,98,0,0,40,0,0,68.516053,0.0,0.0,0.0,952.0,952.0,0.0,0.0,1916.0,1.0,192.0
2576,3,3,0,0,5,3,6,4,1,3,3,0,5.0,1.0,1.0,0.0,3.0,0.0,1.0,0.0,7.0,2.0,2.0,0.0,2.0,3.0,0.0,3.0,14.0,2.0,3.0,4.0,4.0,4.0,1.0,1.0,0.0,1.0,2.0,4.0,1.0,9.0,4.0,5.0,8.0,3.0,1733,139600,13680,3,5,1955,1955,1733,0,0,2,0,4,1,8,1,0,0,0,0,0,0,0,68.516053,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955.0,2.0,452.0
2577,3,3,3,3,3,3,8,0,1,3,3,0,4.0,1.0,1.0,3.0,1.0,0.0,4.0,0.0,6.0,2.0,2.0,2.0,5.0,1.0,0.0,8.0,8.0,2.0,1.0,3.0,1.0,6.0,1.0,0.0,0.0,0.0,2.0,4.0,1.0,9.0,4.0,15.0,10.0,1.0,2002,145000,6270,5,6,1949,1950,1001,1001,0,2,0,4,2,8,0,0,0,0,0,0,0,0,82.000000,0.0,284.0,0.0,717.0,1001.0,0.0,0.0,1949.0,3.0,871.0
2578,4,3,4,3,5,4,8,3,3,3,3,0,5.0,1.0,1.0,3.0,3.0,0.0,4.0,0.0,5.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,1.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,9.0,1.0,1842,217500,8826,7,5,2000,2000,985,857,0,2,1,3,1,7,1,193,96,0,0,0,0,0,68.516053,144.0,841.0,0.0,144.0,985.0,1.0,0.0,2000.0,2.0,486.0
2579,4,3,4,3,5,4,8,3,2,3,3,0,5.0,1.0,1.0,0.0,3.0,0.0,4.0,0.0,23.0,2.0,2.0,0.0,5.0,1.0,0.0,12.0,13.0,1.0,2.0,3.0,2.0,6.0,1.0,1.0,3.0,1.0,2.0,4.0,1.0,9.0,4.0,10.0,11.0,0.0,1911,215000,9554,8,5,1993,1994,1065,846,0,2,1,3,1,8,1,182,81,0,0,0,0,0,80.000000,125.0,380.0,0.0,397.0,777.0,0.0,0.0,1993.0,2.0,471.0

In [370]:
new_df.to_csv('BaseOrdinalSHNew.csv')